# Generated by Django 5.2.8 on 2026-09-06 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Имя и фамилия")),
                ("email", models.EmailField(max_length=254, verbose_name="Электронная почта")),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Введите корректный номер телефона в формате +7 (XXX) XXX-XX-XX",
                                regex="^\\+7\\s?$?\\d{3}$?[\\s\\-]?\\d{3}[\\s\\-]?\\d{2}[\\s\\-]?\\d{2}\\$",
                            )
                        ],
                        verbose_name="Телефон",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
                ("accepted_policy", models.BooleanField(default=False, verbose_name="Согласие с политикой")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Сообщение из формы",
                "verbose_name_plural": "Сообщения из формы",
                "ordering": ["-created_at"],
            },
        ),
    ]
