# Generated by Django 5.2.8 on 2026-09-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Сообщение из формы обратной связи",
                "verbose_name_plural": "Сообщения из формы обратной связи",
            },
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Телефон"),
        ),
    ]
