# Generated by Django 5.2.8 on 2026-05-31 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0001_initial"),
        ("users", "0004_alter_teacher_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
        migrations.AlterModelOptions(
            name="testquestionanswer",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Ответ ученика: вопрос с пустым полем ответа",
                "verbose_name_plural": "Ответы учеников: вопросы с пустым полем ответа",
            },
        ),
        migrations.AlterModelOptions(
            name="testquestionelement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Элемент теста: вопрос с пустым полем ответа",
                "verbose_name_plural": "Элементы теста: вопросы с пустым полем ответа",
            },
        ),
        migrations.CreateModel(
            name="LessonClassAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Назначен"),
                ),
                (
                    "deadline",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дедлайн"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "class_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="users.class",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="lessons.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение урока классу",
                "verbose_name_plural": "Назначения уроков классам",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonUserAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Завершен"),
                ),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="Оценка"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "class_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="lessons.lessonclassassignment",
                        verbose_name="Назначение урока",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение урока ученику",
                "verbose_name_plural": "Назначения уроков ученикам (Автоматически)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="testquestionanswer",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answersQuestion",
                to="lessons.lessonuserassignment",
                verbose_name="Назначение урока",
            ),
        ),
        migrations.DeleteModel(
            name="LessonAssignment",
        ),
    ]
