# Generated by Django 5.2.8 on 2026-05-31 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lessons",
            "0002_alter_test_options_alter_testquestionanswer_options_and_more",
        ),
        ("users", "0004_alter_teacher_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonChildAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Завершен"),
                ),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="Оценка"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Назначение урока ученику",
                "verbose_name_plural": "Назначения уроков ученикам (Автоматически)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="lessonuserassignment",
            name="class_assignment",
        ),
        migrations.RemoveField(
            model_name="lessonuserassignment",
            name="user",
        ),
        migrations.AddConstraint(
            model_name="lessonclassassignment",
            constraint=models.UniqueConstraint(fields=("lesson", "class_name"), name="unique_class_assignment"),
        ),
        migrations.AddField(
            model_name="lessonchildassignment",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="users.child",
                verbose_name="Ученик",
            ),
        ),
        migrations.AddField(
            model_name="lessonchildassignment",
            name="class_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="lessons.lessonclassassignment",
                verbose_name="Назначение урока",
            ),
        ),
        migrations.AlterField(
            model_name="testquestionanswer",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answersQuestion",
                to="lessons.lessonchildassignment",
                verbose_name="Назначение урока",
            ),
        ),
        migrations.DeleteModel(
            name="LessonUserAssignment",
        ),
    ]
