# Generated by Django 5.2.8 on 2026-06-01 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0003_lessonchildassignment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lessonchildassignment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Назначение урока ученику",
                "verbose_name_plural": "Назначения уроков ученикам",
            },
        ),
        migrations.AlterField(
            model_name="lessonchildassignment",
            name="class_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="lessons.lessonclassassignment",
                verbose_name="Назначение урока классу",
            ),
        ),
        migrations.AlterField(
            model_name="lessonchildassignment",
            name="score",
            field=models.SmallIntegerField(blank=True, null=True, verbose_name="Оценка"),
        ),
        migrations.AlterField(
            model_name="testquestionelement",
            name="points",
            field=models.SmallIntegerField(verbose_name="Балл"),
        ),
        migrations.CreateModel(
            name="TestCheckboxElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkboxes",
                        to="lessons.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент теста: вопрос с чекбоксами",
                "verbose_name_plural": "Элементы теста: вопросы с чекбоксами",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCheckboxVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=80, verbose_name="Ответ")),
                ("points", models.SmallIntegerField(verbose_name="Балл")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "test_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="lessons.testcheckboxelement",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа ученика: вопрос с чекбоксами",
                "verbose_name_plural": "Варианты ответов учеников: вопросы с чекбоксами",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCheckboxAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answersCheckbox",
                        to="lessons.lessonchildassignment",
                        verbose_name="Назначение урока",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="lessons.testcheckboxelement",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "answers",
                    models.ManyToManyField(to="lessons.testcheckboxvariant", verbose_name="Ответы"),
                ),
            ],
            options={
                "verbose_name": "Ответ ученика: вопрос с чекбоксами",
                "verbose_name_plural": "Ответы учеников: вопросы с чекбоксами",
                "ordering": ["-created_at"],
            },
        ),
    ]
