# Generated by Django 5.2.8 on 2026-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0004_alter_lessonchildassignment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testcheckboxvariant",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Элемент теста: варианты для вопроса с чекбоксами",
                "verbose_name_plural": "Элементы теста: варианты для вопросов с чекбоксами",
            },
        ),
        migrations.AddField(
            model_name="testcheckboxanswer",
            name="points",
            field=models.SmallIntegerField(default=0, verbose_name="Полученные баллы"),
            preserve_default=False,
        ),
    ]
