# Generated by Django 5.2.8 on 2026-06-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0005_alter_testcheckboxvariant_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testcheckboxvariant",
            options={
                "ordering": ["-test_element"],
                "verbose_name": "Элемент теста: варианты для вопроса с чекбоксами",
                "verbose_name_plural": "Элементы теста: варианты для вопросов с чекбоксами",
            },
        ),
        migrations.RemoveField(
            model_name="testcheckboxvariant",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="testcheckboxvariant",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_need_vpn",
            field=models.BooleanField(default=False, verbose_name="Требуется VPN"),
        ),
        migrations.AlterField(
            model_name="testcheckboxanswer",
            name="points",
            field=models.SmallIntegerField(default=0, verbose_name="Полученные баллы"),
        ),
    ]
