# Generated by Django 5.2.8 on 2026-07-01 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0006_alter_testcheckboxvariant_options_and_more"),
        ("users", "0004_alter_teacher_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonchildassignment",
            name="in_progress",
            field=models.BooleanField(default=False, verbose_name="В процессе прохождения"),
        ),
        migrations.AlterField(
            model_name="lessonchildassignment",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="users.child",
                verbose_name="Ученик",
            ),
        ),
        migrations.AlterField(
            model_name="lessonchildassignment",
            name="class_assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="lessons.lessonclassassignment",
                verbose_name="Назначение урока классу",
            ),
        ),
        migrations.AddConstraint(
            model_name="testcheckboxanswer",
            constraint=models.UniqueConstraint(fields=("question", "assignment"), name="unique_checkbox_answer"),
        ),
        migrations.AddConstraint(
            model_name="testquestionanswer",
            constraint=models.UniqueConstraint(fields=("question", "assignment"), name="unique_question_answer"),
        ),
    ]
