# Generated by Django 5.2.8 on 2026-07-02 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0007_lessonchildassignment_in_progress_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testcheckboxvariant",
            options={
                "ordering": ["-test_element"],
                "verbose_name": "Вариант элемента теста: варианты для вопроса с чекбоксами",
                "verbose_name_plural": "Варианты элементов теста: варианты для вопросов с чекбоксами",
            },
        ),
        migrations.CreateModel(
            name="TestKeyValueElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Вопрос"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_value",
                        to="lessons.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент теста: вопрос с ключом и значением",
                "verbose_name_plural": "Элементы теста: вопросы с ключом и значением",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestKeyVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, verbose_name="Ключ")),
                ("points", models.SmallIntegerField(default=0, verbose_name="Балл")),
                (
                    "test_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.testkeyvalueelement",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант элемента теста: ключ для вопроса с ключом и значением",
                "verbose_name_plural": "Варианты элементов теста: ключи для вопросов с ключом и значением",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="TestValueVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="Значение")),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessons.testkeyvariant",
                        verbose_name="Ключ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Варианты элемента теста: значение для вопроса с ключом и значением",
                "verbose_name_plural": "Варианты элементов теста: значения для вопросов с ключом и значением",
                "ordering": ["key", "value"],
            },
        ),
        migrations.CreateModel(
            name="TestKeyValueAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.SmallIntegerField(default=0, verbose_name="Полученные баллы"),
                ),
                ("answers", models.JSONField(verbose_name="Ответы")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answersKeyValue",
                        to="lessons.lessonchildassignment",
                        verbose_name="Назначение урока",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="lessons.testkeyvalueelement",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ ученика: вопрос с ключом и значением",
                "verbose_name_plural": "Ответы учеников: вопросы с ключом и значением",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "assignment"),
                        name="unique_key_value_answer",
                    )
                ],
            },
        ),
    ]
