# Generated by Django 5.2.8 on 2026-07-02 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0008_alter_testcheckboxvariant_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testkeyvariant",
            name="test_element",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="keys",
                to="lessons.testkeyvalueelement",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="testvaluevariant",
            name="key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="lessons.testkeyvariant",
                verbose_name="Ключ",
            ),
        ),
    ]
