# Generated by Django 5.2.8 on 2026-07-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0009_alter_testkeyvariant_test_element_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testkeyvariant",
            options={
                "ordering": ["key"],
                "verbose_name": "Ключ",
                "verbose_name_plural": "Ключи",
            },
        ),
        migrations.AlterModelOptions(
            name="testvaluevariant",
            options={
                "ordering": ["key", "value"],
                "verbose_name": "Значение",
                "verbose_name_plural": "Значения",
            },
        ),
        migrations.RemoveField(
            model_name="testquestionanswer",
            name="is_correct",
        ),
        migrations.AddField(
            model_name="testquestionanswer",
            name="points",
            field=models.SmallIntegerField(default=0, verbose_name="Полученные баллы"),
        ),
        migrations.AlterField(
            model_name="testquestionelement",
            name="points",
            field=models.SmallIntegerField(default=1, verbose_name="Балл"),
        ),
    ]
