# Generated by Django 5.2.8 on 2026-07-14 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0010_alter_testkeyvariant_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testquestionanswer",
            name="answer",
            field=models.CharField(max_length=20, verbose_name="Ответ"),
        ),
        migrations.AlterField(
            model_name="testquestionelement",
            name="answer",
            field=models.CharField(max_length=20, verbose_name="Верный ответ"),
        ),
        migrations.CreateModel(
            name="TestEssayElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255, verbose_name="Вопрос")),
                ("points", models.SmallIntegerField(verbose_name="Балл")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essays",
                        to="lessons.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент теста: эссе",
                "verbose_name_plural": "Элементы теста: эссе",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestEssayAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.SmallIntegerField(default=0, verbose_name="Полученные баллы"),
                ),
                ("answer", models.TextField(verbose_name="Ответ")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Проверен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answersEssay",
                        to="lessons.lessonchildassignment",
                        verbose_name="Назначение урока",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="lessons.testessayelement",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ ученика: эссе",
                "verbose_name_plural": "Ответы учеников: эссе",
                "ordering": ["-created_at"],
                "constraints": [models.UniqueConstraint(fields=("question", "assignment"), name="unique_essay_answer")],
            },
        ),
    ]
