# Generated by Django 5.2.8 on 2026-07-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0011_alter_testquestionanswer_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testessayelement",
            name="points",
            field=models.SmallIntegerField(verbose_name="Максимальное количество баллов"),
        ),
        migrations.AlterField(
            model_name="testessayelement",
            name="question",
            field=models.CharField(max_length=1000, verbose_name="Вопрос"),
        ),
    ]
