# Generated by Django 5.2.8 on 2026-07-30 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0012_alter_testessayelement_points_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonclassassignment",
            name="assigned_at",
        ),
    ]
