# Generated by Django 5.2.8 on 2026-08-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0013_remove_lessonclassassignment_assigned_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="image",
            field=models.ImageField(blank=True, upload_to="lessons", verbose_name="Изображение"),
        ),
    ]
