# Generated by Django 5.2.8 on 2026-09-01 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0014_lesson_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testessayelement",
            name="question",
            field=models.CharField(max_length=500, verbose_name="Вопрос"),
        ),
        migrations.CreateModel(
            name="TestEssayAiElement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=500, verbose_name="Вопрос")),
                ("points", models.SmallIntegerField(verbose_name="Максимальное количество баллов")),
                (
                    "mention_things",
                    models.CharField(max_length=500, verbose_name="Что должен упомянуть(влияет на оценку)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="essays_ai",
                        to="lessons.test",
                        verbose_name="Тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент теста: эссе с ИИ",
                "verbose_name_plural": "Элементы теста: эссе с ИИ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestEssayAiAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("points", models.SmallIntegerField(default=0, verbose_name="Полученные баллы")),
                ("answer", models.TextField(verbose_name="Ответ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answersEssayAi",
                        to="lessons.lessonchildassignment",
                        verbose_name="Назначение урока",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="lessons.testessayaielement",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ ученика: эссе с ИИ",
                "verbose_name_plural": "Ответы учеников: эссе с ИИ",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("question", "assignment"), name="unique_essay_ai_answer")
                ],
            },
        ),
    ]
