# Generated by Django 5.2.8 on 2026-09-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0015_alter_testessayelement_question_testessayaielement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiErrorRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("error", models.TextField(verbose_name="Текст ошибки")),
                ("code", models.IntegerField(verbose_name="Код ошибки")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "essay_ai_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="lessons.testessayaianswer",
                        verbose_name="Ответ ученика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ошибка запроса к ИИ",
                "verbose_name_plural": "Ошибки запросов к ИИ",
                "ordering": ["-created_at"],
            },
        ),
    ]
