# Generated by Django 5.2.8 on 2026-09-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0016_aierrorrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testessayaielement",
            name="points",
            field=models.PositiveSmallIntegerField(verbose_name="Максимальное количество баллов"),
        ),
    ]
