# Generated by Django 5.2.8 on 2026-09-14 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0017_alter_testessayaielement_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testessayaielement",
            name="points",
            field=models.PositiveSmallIntegerField(
                help_text="От 1 до 32\xa0767",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name="Максимальное количество баллов",
            ),
        ),
    ]
