# Generated by Django 5.2.8 on 2026-09-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0018_alter_testessayaielement_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonchildassignment",
            name="recommend",
            field=models.TextField(blank=True, null=True, verbose_name="Рекомендации после прохождения"),
        ),
    ]
