# Generated by Django 5.2.8 on 2026-09-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0019_lessonchildassignment_recommend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testessayaielement",
            name="mention_things",
            field=models.TextField(verbose_name="Что должен упомянуть(влияет на оценку)"),
        ),
    ]
