# Generated by Django 5.2.8 on 2026-09-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0020_lesson_is_video_360"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["-created_at"], "verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
        migrations.AlterField(
            model_name="testessayaielement",
            name="mention_things",
            field=models.TextField(verbose_name="Что должен упомянуть(влияет на оценку)"),
        ),
    ]
