# Generated by Django 5.2.8 on 2026-05-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(
                help_text="Не более 100 символов.",
                max_length=100,
                verbose_name="Название",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("name", "school")},
        ),
    ]
