# Generated by Django 5.2.8 on 2026-09-06 22:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_teacher_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"ordering": ["school", "name"], "verbose_name": "Класс", "verbose_name_plural": "Классы"},
        ),
    ]
