# Generated by Django 5.2.8 on 2026-09-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_class_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Если галочка не стоит — пользователь не сможет войти на сайт.",
                verbose_name="Активен",
            ),
        ),
    ]
